aljeter: Drop telephony HAL build
This already include in AOSPA source and it caused

Runtime aborting...
All threads:
DALVIK THREADS (1):
"main" prio=5 tid=1 Runnable (still starting up)
  | group="" sCount=0 ucsCount=0 flags=0 obj=(nil) self=0x56315c37ca40
  | sysTid=3885 nice=0 cgrp=default sched=0/0 handle=0x7fa9aa98b740
  | state=R schedstat=( 472598851 104993929 608 ) utm=40 stm=7 core=34 HZ=100
  | stack=0x7fffda5f9000-0x7fffda5fb000 stackSize=8188KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 0000000000da2e68  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (UnwindStackCurrent::UnwindFromContext(unsigned long, void*)+88)
  native: #01 pc 0000000000d9dc18  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+136)
  native: #02 pc 0000000000e433dc  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+396)
  native: #03 pc 0000000000e6c3f6  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::DumpCheckpoint::Run(art::Thread*)+582)
  native: #04 pc 0000000000e650d2  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+290)
  native: #05 pc 0000000000e64cb0  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool)+368)
  native: #06 pc 0000000000d36f8a  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+186)
  native: #07 pc 0000000000d20a56  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Abort(char const*)+406)
  native: #08 pc 000000000169addc  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+60)
  native: #09 pc 000000000169aa65  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (android::base::LogMessage::~LogMessage()+341)
  native: #10 pc 0000000000713288  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::ClassLinker::AddExtraBootDexFiles(art::Thread*, std::__1::vector<std::__1::unique_ptr<art::DexFile const, std::__1::default_delete<art::DexFile const> >, std::__1::allocator<std::__1::unique_ptr<art::DexFile const, std::__1::default_delete<art::DexFile const> > > >&&)+696)
  native:   __compressed_pair_elem
  native:    external/libcxx/include/memory:2140
  native:   __compressed_pair<true, void>
  native:    external/libcxx/include/memory:2234
  native:   basic_string<nullptr_t>
  native:    external/libcxx/include/string:820
  native:   UnwindStackCurrent::UnwindFromContext(unsigned long, void*)
  native:    system/unwinding/libbacktrace/UnwindStack.cpp:169
  native: #11 pc 0000000000d25d6b  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Init(art::RuntimeArgumentMap&&)+18827)
  native:   art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)
  native:    art/runtime/native_stack_dump.cc:335 (discriminator 2)
  native: #12 pc 0000000000d2138a  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Create(art::RuntimeArgumentMap&&)+74)
  native: #13 pc 0000000000480bcf  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Dex2Oat::CreateRuntime(art::RuntimeArgumentMap&&)+127)
  native: #14 pc 0000000000473351  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Dex2Oat::Setup()+2081)
  native: #15 pc 000000000046da76  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (main+1414)
  native: #16 pc 000000000002d30f  /usr/lib/libc.so.6 (__libc_start_call_main+127)
  native:   __libc_start_call_main
  native:    libc-start.c:?
  native: #17 pc 000000000002d3c0  /usr/lib/libc.so.6 (__libc_start_main+128)
  native:   __libc_start_main_alias_2
  native:    :?
  native: #18 pc 0000000000416528  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (???)
  (no managed stack frames)

dex2oatd E 04-01 20:52:48  3885  3885 thread-inl.h:158] holding "abort lock" at point where thread suspension is expected
Aborting thread:
"main" prio=5 tid=1 Runnable (still starting up)
  | group="" sCount=0 ucsCount=0 flags=0 obj=(nil) self=0x56315c37ca40
  | sysTid=3885 nice=0 cgrp=default sched=0/0 handle=0x7fa9aa98b740
  | state=R schedstat=( 631789164 189322713 675 ) utm=55 stm=8 core=18 HZ=100
  | stack=0x7fffda5f9000-0x7fffda5fb000 stackSize=8188KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 0000000000da2e68  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (UnwindStackCurrent::UnwindFromContext(unsigned long, void*)+88)
  native: #01 pc 0000000000d9dc18  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+136)
  native: #02 pc 0000000000e433dc  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+396)
  native:   __compressed_pair_elem
  native:    external/libcxx/include/memory:2140
  native:   __compressed_pair<true, void>
  native:    external/libcxx/include/memory:2234
  native:   basic_string<nullptr_t>
  native:    external/libcxx/include/string:820
  native:   UnwindStackCurrent::UnwindFromContext(unsigned long, void*)
  native:    system/unwinding/libbacktrace/UnwindStack.cpp:169
  native: #03 pc 0000000000d3725d  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+93)
  native:   art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)
  native:    art/runtime/native_stack_dump.cc:335 (discriminator 2)
  native: #04 pc 0000000000d20a56  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Abort(char const*)+406)
  native: #05 pc 000000000169addc  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+60)
  native: #06 pc 000000000169aa65  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (android::base::LogMessage::~LogMessage()+341)
  native: #07 pc 0000000000713288  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::ClassLinker::AddExtraBootDexFiles(art::Thread*, std::__1::vector<std::__1::unique_ptr<art::DexFile const, std::__1::default_delete<art::DexFile const> >, std::__1::allocator<std::__1::unique_ptr<art::DexFile const, std::__1::default_delete<art::DexFile const> > > >&&)+696)
  native: #08 pc 0000000000d25d6b  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Init(art::RuntimeArgumentMap&&)+18827)
  native: #09 pc 0000000000d2138a  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Runtime::Create(art::RuntimeArgumentMap&&)+74)
  native: #10 pc 0000000000480bcf  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Dex2Oat::CreateRuntime(art::RuntimeArgumentMap&&)+127)
  native: #11 pc 0000000000473351  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (art::Dex2Oat::Setup()+2081)
  native: #12 pc 000000000046da76  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (main+1414)
  native: #13 pc 000000000002d30f  /usr/lib/libc.so.6 (__libc_start_call_main+127)
  native:   __libc_start_call_main
  native:    libc-start.c:?
  native: #14 pc 000000000002d3c0  /usr/lib/libc.so.6 (__libc_start_main+128)
  native:   __libc_start_main_alias_2
  native:    :?
  native: #15 pc 0000000000416528  /srv/media/build/aospa/out/soong/host/linux-x86/bin/dex2oatd64 (???)
  (no managed stack frames)
ERROR: Dex2oat failed to compile a boot image.It is likely that the boot classpath is inconsistent.Rebuild with ART_BOOT_IMAGE_EXTRA_ARGS="--runtime-arg -verbose:verifier" to see verification errors.

Change-Id: Ief2a0d6b77e443dda9da905b03d35c906a18b13f
Signed-off-by: Jprimero15 <jprimero155@gmail.com>